### PR TITLE
some low hanging fruit...

### PR DESCRIPTION
**Pull request by stewpend0us**
Added Comment to the ast. Just looking for a simple place to start. Wasn't really sure what to do in test_ast.py. Also wasn't sure if I should put a test in test_ccode.py or not.

The printer (for ccode at least) doesn't seem to support /* multi line comments */ (if the string contains \n for example) Would that be implemented as a new type? or should ccode._get_comment() handle that? I could also see it being an option passed in a kwarg to _get_comment but it doesn't have kwargs right now.

### CODE REVIEW

**Comment by bjodah** [comment]
Looks like a good start. As you can see in the failed CI job logs you need to add a test for `Comment` in `sympy/core/tests/test_args.py`.

What about only supporting `/* comment-text /*` style comments? I think the `//` syntax isn't supported by all C compilers for old standards. Then the comment may also appear inside statements, e.g.:
```C
double cse1 = x*x + 1.0;
// more code...
double cse932 = x*y - z;
// more code...
return sqrt(cse1 /* x*x + 1.0 */) - sin(cse932 /* x*y - z */);
```
(not that this in particular would be terribly useful, but I could imagine things something along those lines still) 

We should probably add a test where in `test_ccode.py` where it is applied together with some code
(that way we are forced to figure out how to introduce `Comment` nodes into our trees).

**Comment by stewpend0us** [comment]
I agree with switching to the /**/ style comments. Does it make sense to make that change in this branch though?

Also do most languages support putting a comment in line? It seems like a silly feature to write (in general :P but especially) if it's only supported by c...It would be helpful for me in understanding how the ast code works though.

**Comment by bjodah** [comment]
You're right: can't think of inline comments being supported in other languages (though I do use them to silence compiler warnings with respect to unused parameters, but that's a different topic).

**Comment by bjodah** [comment]
And you're right, let's change to the `/* */` style in the SymPy main repo (but at some much later stage after the big PR has been merged since it will require tons of updates to tests and we are already changing quite a few things)

**Pull request merged**
