### PR TITLE
wrote a failing test for CodeBlock.cse()

### PR DESCRIPTION
**Pull request by stewpend0us**
wrote a failing test for CodeBlock.cse() I could have the assertion wrong but the .cse() method actually fails to run. I tracked it down to cse_main.py -> _rebuild(expr): -> if iterable(expr): when expr is a tuple of (more than 1) Matrix the _rebuild method doesn't correctly rebuild the elements of the tuple. Matrix class is expecting (Matrix([..]),) as it's arguments but it's getting Matrix([..]) (missing the sinlge element tuple) I don't konw if that's a problem with the matrix stuff or the cse stuff....but either way :(

Sorry if this is the wrong place for this kind of thing...

### CODE REVIEW

**Comment by bjodah** [comment]
Nice catch. I dug into this a little and the problem seems to appear even outside the context of `sympy.codegen.ast`:
```python
>>> x0 = Symbol('x0')
>>> m1, m2 = Matrix([[x, sin(y)],[3, 4]]), Matrix([[sin(y), 2*sin(y)], [sin(y)**2, 7]])
>>> t = Tuple(m1, m2)  # the error only occurs then wrapping these in tuple, e.g. list is fine
>>> cse(t)
...
TypeError: Data type not understood
```
I opened https://github.com/sympy/sympy/issues/14118 since we should fix this in SymPy master regardless of sympy/sympy#13100

**Comment by stewpend0us** [comment]
Ok that test is valid though isn't it? Any reason not to merge it in?

**Comment by bjodah** [comment]
It's definitely valid and I will merge this PR (thanks!).
I was just thinking that if we can fix sympy/sympy#14118 in master first, then we can merge this in without it failing. I can of course merge this immediately if you prefer me to do so?

**Comment by stewpend0us** [comment]
No that's fine! Just checking :) I'm very new to this so I'm not sure what the etiquette is yet.

**Comment by bjodah** [comment]
I cherry-picked your commit 3c6e7b9833608d8c78b0408d11715259883ca2bf into https://github.com/sympy/sympy/pull/13100 (commit 9ee6236)

**Pull request closed without merging**
